// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_api.Models;

namespace dotnet_api.Migrations
{
    [DbContext(typeof(AlacenaContext))]
    [Migration("20211115065808_db_creation")]
    partial class db_creation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnet_api.Models.ProductModel", b =>
                {
                    b.Property<string>("idProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("barCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("nameProduct")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idProduct");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
